### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by wooorm** [3axap4eHko/xast#1]
Hi Ivan!

We at https://unifiedjs.com have been using the name `xast` for our XML ast for a couple years now: https://github.com/syntax-tree/xast. (similar to [mdast](https://github.com/syntax-tree/mdast), [hast](https://github.com/syntax-tree/hast), [nlcst](https://github.com/syntax-tree/nlcst), and others).
Our `xast`-related packages are not super popular, but still, they’re used by a bunch of people for one or two years already.

We haven’t published an `xast` package itself, because that would be a types-only package, and thus we maintain it in DefinitelyTyped.

In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62010#issue-1354589712, it was noticed that this will conflict for users who would have both projects in their `node_modules`.

Due to this conflict, the potential confusion with two AST-related projects with the same name, and how recent this package is, I was hoping that you would consider a different name for this project?

**Comment by siefkenj** [comment]
@3axap4eHko It looks like you have a great project here, but I accidentally installed `xast` in addition to `@types/xast` today and it took me quite a while to figure out that they were unrelated projects...

Would you consider renaming your project? Have you considered the name `xml-ast`? It appears to be available on npm.

**Comment by 3axap4eHko** [comment]
@siefkenj I believe software engineers should not blindly install any packages.

**Comment by siefkenj** [comment]
> @siefkenj I believe software engineers should not blindly install any packages.

You're absolutely right, and it was unifiedjs's mistake not to register the package name when they registered the `@types` package, but maybe you could help them out?

**Comment by wooorm** [comment]
Hi Ivan! I was wondering if you might have changed your mind already?
Typo squatting and phishing is a real problem on npm. More and more so every day.
I would really appreciate it if you could use a different name, because humans keep running into this!
